server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect # JDK8과 Gradle5버전을 사용하면 해당 환경을 지원하는 MySQL이면서 8과 호환되는 것
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

  thymeleaf:
    mode: LEGACYHTML5

  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG

# Redisson configuration file
redisson-config: classpath:conf/redisson.yaml

management:
  security:
    enabled: true
    roles: ROLE_ADMIN
